baseurl: "/"
title: "Programming for Statistical Science"
author: "Colin Rundel"
copyright: "&copy; 2021. All rights reserved."
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir: "docs"

menu:
  main:
  - name: Home
    pre: <i class='fa fa-home fa-fw'></i>
    weight: 1
    identifier: home
    url: "#schedule"  
  - name: Syllabus
    pre: <i class='fa fa-file-text-o fa-fw'></i>
    weight: 2
    identifier: syllabus
    url: "#syllabus"
  - name: Sakai
    pre: <i class="fas fa-comment fa-fw"></i>
    weight: 3
    url: https://sakai.duke.edu/portal/site/04b2b1c4-1d06-47ce-9e6e-50d3c2635125
  - name: Github
    pre: <i class='fa fa-github fa-fw'></i>
    weight: 6
    url: https://github.com/sta523-fa21
  - name: RStudio
    pre: <i class='fab fa-r-project fa-fw'></i>
    weight: 7
    url: https://rstudio.stat.duke.edu:8787

params:
  subtitle: "(Fall 2021)"
  course: "Sta 523"
  highlightjs: androidstudio
  highlightjs_extra_languages:
    - yaml
  dateFormat: '02 Jan 2006, 15:04'
  sections:
    - schedule
    - syllabus
    - textbooks
    - about
  contact:
    - name: Dr. Colin Rundel
      office:
      email: colin.rundel@duke.edu
      hours: TBD
  assignments:
    - name: Homework
      type: Team
      value: 40%
    - name: Midterms
      value: 40%
    - name: Project
      value: 20%
